package db

import (
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	gorm_logger "gorm.io/gorm/logger"
)

var DB *gorm.DB

func ConnectDB(dsn string) (error) {
	/**
	|-------------------------------------------------------------------------
	| Code generated by tekit-gen-project with database option.
	| @notice: exactly the same as the built-in
	|-----------------------------------------------------------------------*/
	dbConn, err := gorm.Open(mysql.Open(dsn), &gorm.Config{
		Logger: gorm_logger.Default.LogMode(gorm_logger.Info),
	})
	if err != nil {
		return err
	}

	DB = dbConn
	return nil
}
